# Generated by Django 4.1.7 on 2023-03-21 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand_fondator', models.CharField(max_length=400)),
                ('brand_name', models.CharField(max_length=400)),
                ('brand_rank', models.CharField(max_length=400)),
                ('nr_models', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('color', models.CharField(max_length=400)),
                ('model_wearing', models.CharField(max_length=400)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dresses', to='dresses.brand')),
            ],
        ),
        migrations.CreateModel(
            name='RedCarpetPresentation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('holder', models.CharField(max_length=200)),
                ('city_name', models.CharField(max_length=200)),
                ('special_guest', models.CharField(max_length=200)),
                ('event_name', models.CharField(max_length=200)),
                ('nr_guests', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShowEvent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pieces', models.IntegerField()),
                ('show_date', models.CharField(max_length=200)),
                ('show_popularity', models.IntegerField()),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dresses.dress')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dresses.redcarpetpresentation')),
            ],
        ),
    ]
