# Generated by Django 4.1.7 on 2023-03-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='price',
            field=models.IntegerField(default=90),
        ),
    ]
