# Generated by Django 4.1.7 on 2023-03-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dresses', '0002_dress_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='redcarpetpresentation',
            name='dresses',
            field=models.ManyToManyField(through='dresses.ShowEvent', to='dresses.dress'),
        ),
    ]
